name: Noty flatpak bundle release

on:
  push:
    tags:
      - "v*"

jobs:
  binary-builder:
    name: "Binary Builder"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build python3-pip python3-dev gettext libglib2.0-dev-bin desktop-file-utils gobject-introspection libgtk-4-dev gir1.2-gtk-4.0 libadwaita-1-dev libgirepository1.0-dev
      - name: Install python dependencies
        run: |
          pip install pygobject
          pip install pygobject-stubs
      - name: Install blueprint-compiler from source
        run: |
          git clone https://gitlab.gnome.org/jwestman/blueprint-compiler
          cd blueprint-compiler
          meson _build
          sudo ninja -C _build install
          cd ..
          # Verify blueprint-compiler installation
          blueprint-compiler --version
      - name: Build Binary
        run: |
          meson setup build
          ninja -C build
          tar -czf noty-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.tar.gz -C build/src noty
      - name: Upload Binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: noty-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.tar.gz
          path: noty-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.tar.gz
          if-no-files-found: error

  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Build Flatpak
        run: |
          flatpak-builder --repo=repo --force-clean flatpak_app build-aux/flatpak/com.dagimg.noty.json
          flatpak build-bundle repo noty-${{ steps.get_version.outputs.VERSION }}.flatpak com.dagimg.noty
          ls -la
      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: noty-${{ steps.get_version.outputs.VERSION }}.flatpak
          path: noty-${{ steps.get_version.outputs.VERSION }}.flatpak
          if-no-files-found: error

  release:
    name: "Create Release"
    needs: [flatpak-builder, binary-builder]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Download Flatpak bundle
        uses: actions/download-artifact@v4
        with:
          name: noty-${{ steps.get_version.outputs.VERSION }}.flatpak
      - name: Download Binary bundle
        uses: actions/download-artifact@v4
        with:
          name: noty-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.tar.gz
      - name: List files
        run: ls -la
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            noty-${{ steps.get_version.outputs.VERSION }}.flatpak
            noty-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.tar.gz
          generate_release_notes: true
